# Generated by Django 4.1.5 on 2023-02-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='FULL NAME')),
                ('emailid', models.EmailField(max_length=100, verbose_name='EMAIL ID')),
                ('contact', models.IntegerField(verbose_name='Contact Number')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
            ],
        ),
    ]
